CREATE TABLE PRICE(
    PRICE_ID BIGINT NOT NULL,
    BRAND_ID BIGINT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE_LIST_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE FLOAT NOT NULL,
    CURRENCY VARCHAR NOT NULL,

    CONSTRAINT PK_PRICE PRIMARY KEY (PRICE_ID)
);